"""Deterministic mock generator for testing."""

_DEFAULT_RESPONSE = (
    "Based on the provided context, the answer is that this is a test response "
    "generated by the mock generator for development and testing purposes."
)


class MockGenerator:
    def __init__(self, fixed_response: str | None = None) -> None:
        self._response = fixed_response or _DEFAULT_RESPONSE

    def generate(self, system_prompt: str, user_prompt: str) -> str:
        _ = system_prompt, user_prompt
        return self._response

    def model_name(self) -> str:
        return "mock-generator"
