"""Agentic RAG pipeline: multi-query decomposition for complex questions."""

from pathlib import Path


def ingest(source_dir: str | Path) -> int:
    # Generated by rag-forge init agentic
    print(f"Ingesting documents from {source_dir}...")
    return 0


def query(question: str, top_k: int = 5) -> str:
    # Generated by rag-forge init agentic
    # Run via: rag-forge query "question" --agent-mode
    print(f"Agentic query: {question} (top_k={top_k})")
    return "Pipeline not yet configured. Run: rag-forge index --source ./docs"


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        print(query(" ".join(sys.argv[1:])))
    else:
        print("Usage: python pipeline.py <your complex question>")
