"""Hybrid RAG pipeline: BM25 + vector search with reranking and enrichment."""

from pathlib import Path


def ingest(source_dir: str | Path, enrich: bool = True) -> int:
    """Ingest documents with hybrid indexing and optional enrichment.

    Returns chunk count. Run via CLI:
        rag-forge index --source ./docs --enrich --sparse-index-path .rag-forge/sparse
    """
    # Generated by rag-forge init hybrid
    # Customize this pipeline to fit your use case
    print(f"Ingesting documents from {source_dir} (enrich={enrich})...")
    return 0


def query(question: str, top_k: int = 5, alpha: float = 0.6) -> str:
    """Query with hybrid retrieval (dense + BM25 + reranking).

    Run via CLI:
        rag-forge query "your question" --strategy hybrid --alpha 0.6 --reranker cohere
    """
    # Generated by rag-forge init hybrid
    print(f"Querying: {question} (top_k={top_k}, alpha={alpha})")
    return "Pipeline not yet configured. Run: rag-forge index --source ./docs --enrich"


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        answer = query(" ".join(sys.argv[1:]))
        print(answer)
    else:
        print("Usage: python pipeline.py <your question>")
