"""Basic RAG pipeline: ingest documents, retrieve chunks, generate answers."""

from pathlib import Path


def ingest(source_dir: str | Path) -> int:
    """Ingest documents from a directory. Returns chunk count."""
    # Generated by rag-forge init basic
    # Customize this pipeline to fit your use case
    print(f"Ingesting documents from {source_dir}...")
    return 0


def query(question: str, top_k: int = 5) -> str:
    """Query the RAG pipeline. Returns generated answer."""
    # Generated by rag-forge init basic
    print(f"Querying: {question} (top_k={top_k})")
    return "Pipeline not yet configured. Run: rag-forge index --source ./docs"


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        answer = query(" ".join(sys.argv[1:]))
        print(answer)
    else:
        print("Usage: python pipeline.py <your question>")
